#!/usr/bin/env python3
"""
Convert a prepared MP4/video into frame_0000.py, frame_0001.py, ... files
compatible with gmpak_pack_v2.py's MockGint parser.

This does not require the fxconv CLI --py mode. It imports tools/fxconv.py
(or a path you pass with --fxconv) and uses the same CG image encoder.
"""
import argparse
import importlib.util
import os
import shutil
import sys
from pathlib import Path

import cv2
from PIL import Image


def load_fxconv(path: str):
    path = os.path.abspath(path)
    spec = importlib.util.spec_from_file_location("fxconv_local", path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"Cannot load fxconv module from {path}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def write_gint_image_py(out_path: Path, name: str, profile_id: int, width: int, height: int,
                        stride: int, color_count: int, data: bytes, palette: bytes):
    palette = palette or b""
    # Keep this deliberately simple: gmpak_pack_v2.py executes it with env={'gint': MockGint()}.
    # Do NOT emit 'import gint', or the mock environment won't catch it.
    out_path.write_text(
        "# Auto-generated by video_frames_to_fxconv_py.py\n"
        "# Compatible with gmpak_pack_v2.py parse_fxconv_py().\n"
        f"{name} = gint.image({profile_id}, {width}, {height}, {stride}, {color_count}, "
        f"{bytes(data)!r}, {bytes(palette)!r})\n",
        encoding="utf-8",
    )


def convert_video_to_fxconv_py(video: str, out_dir: str, fxconv_path: str, profile: str = "p4_rgb565",
                               symbol_prefix: str = "frame", clean: bool = True,
                               save_png: bool = False) -> int:
    fxconv = load_fxconv(fxconv_path)
    cg_profile = fxconv.CgProfile.find(profile)
    if cg_profile is None:
        raise ValueError(f"Unknown CG profile {profile!r}; try rgb565, p8_rgb565, or p4_rgb565")

    out = Path(out_dir)
    if clean and out.exists():
        shutil.rmtree(out)
    out.mkdir(parents=True, exist_ok=True)
    png_dir = out / "png"
    if save_png:
        png_dir.mkdir(parents=True, exist_ok=True)

    cap = cv2.VideoCapture(video)
    if not cap.isOpened():
        raise RuntimeError(f"Could not open video: {video}")

    i = 0
    try:
        while True:
            ok, frame_bgr = cap.read()
            if not ok:
                break

            frame_rgb = cv2.cvtColor(frame_bgr, cv2.COLOR_BGR2RGB)
            img = Image.fromarray(frame_rgb).convert("RGBA")

            data, stride, palette, color_count = fxconv.image_encode(img, cg_profile)
            py_path = out / f"{symbol_prefix}_{i:04d}.py"
            write_gint_image_py(
                py_path, "image", cg_profile.id, img.width, img.height,
                stride, color_count, bytes(data), bytes(palette or b"")
            )

            if save_png:
                img.convert("RGB").save(png_dir / f"{symbol_prefix}_{i:04d}.png")

            if i % 25 == 0:
                print(f"converted frame {i}")
            i += 1
    finally:
        cap.release()

    print(f"Done: wrote {i} fxconv Python frame files into {out}")
    return i


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description="Convert a prepared video into fxconv/gint Python frame files")
    ap.add_argument("video", help="Input MP4/video, ideally already resized/FPS-reduced by enc3.py")
    ap.add_argument("out_dir", help="Output folder for frame_0000.py, frame_0001.py, ...")
    ap.add_argument("--fxconv", default="tools/fxconv.py", help="Path to fxconv.py")
    ap.add_argument("--profile", default="p4_rgb565", help="CG profile: p4_rgb565, p8_rgb565, rgb565, ...")
    ap.add_argument("--prefix", default="frame", help="Filename prefix, default: frame")
    ap.add_argument("--no-clean", action="store_true", help="Do not delete out_dir before writing")
    ap.add_argument("--save-png", action="store_true", help="Also save preview PNGs in out_dir/png")
    args = ap.parse_args(argv)

    convert_video_to_fxconv_py(
        args.video, args.out_dir, args.fxconv, args.profile,
        symbol_prefix=args.prefix, clean=not args.no_clean, save_png=args.save_png,
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
